--- #YAML:1.0
name:                Time-Format
version:             1.11
abstract:            Easy-to-use date/time formatting.
license:             ~
author:              
    - Eric Roode <roode@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::Simple:                  0.40
    Time::Local:                   1.07
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
